version: '2'
services:
  app:
    build: .
    container_name: "app"
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - NODE_ENV=PRODUCAO
      - MONGO_URI=mongodb://mongodb:27017
    links:
      - mongodb
    depends_on:
      - mongodb

  
  mongodb:
    image: mongo:4.0.0-xenial
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db

